notifications:
  email:
    recipients:
      - sebastian@jaenicke.org

language: java

dist: bionic

sudo: required

jdk: openjdk11

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.m2

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq protobuf-compiler
  - git clone -b utilities_2_0 https://github.com/MGX-metagenomics/utilities.git
  - cd utilities && mvn -q clean install -DskipTests=true && cd .. && rm -rf utilities
  - git clone -b GPMS_2_0 https://github.com/MGX-metagenomics/GPMS.git
  - cd GPMS && mvn -q clean install -DskipTests=true && cd .. && rm -rf GPMS

install: true

script:
  - mvn clean install
